language: ruby
cache: bundler
before_install:
- nvm install node
install:
- bundle install
- npm install
script: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec rake site:deploy --quiet; else echo "PR skip deploy"; exit 0; fi
rvm:
- 2.4.0
env:
  global:
  - secure: CopZP4Ph/8gZlYH/vyWIMb+etUlxg+AaS2Y175c2gP0tdWnTC5UaGr+mxnt5uHeVeNsM3kNNHoBRhY6eZUidv7NN5UhXyD87wUDpV3S/gtUFfhWI5exw5TowupsbWxuQthDQ1mhcc6sGHH1zNw6dsVRLDjFEEyZ2IPGu3T8hZiABYUxj6YI4lLq752GJ2xzMS3Di0dI6OVACvZrbVuQ3RzdnWgdb9ye3fyTcrapPD0r3lEpMwCH3iL62U1S8BIc2udIiinwM/QACtyusfoKm91NWmVepX6neWeKkGMM7+YOkUODx7WIL98htjMwqZdK64HgsC66aMlEVyfKdKqtLC5ugDfFirwnBfjunziM5TjsXhS12zf4eMs6+eBqUQnPOIVOGJ2/YMpkFrXM+P7GrCKlbSMlqGSqNWe68T7Do81f8R7tQzGrL0/XXD8/EubN+y7xVp+xpADWMZwKf3ktMiYRbOI1OMjuLEoTmJHfFnTnYgxhjnfb9vCbjR76I4IIDToQ4UXrfZV6dLrbN+bjrOuBqn5sgEm1AMAOMBTsXdTDGfEYlZ2p81HteHH9SA9yrGGStWByWcL3NRuID+8UFAIDydobVQ6nkvskA5bBPS6VcKPcsRKgmJMOcwV50CB3lqKdP2hr3jSPmW+YoxjQAEyPz9/Xa3LHi6pcePJOYqQw=
  - secure: s6R4CnhMcL4blgWOJFNYQeoqxWvCGqSSsMP1sK94NusBji55I93QJpTLZurU5TfcI4fCCFNtqtgxCpmSToFokGmoBG/8b6/ZPiAgngYycq3ahc3EhFiC90ckUTyNV8nhC5y1LE6dV3Ttkm1jubzN23G9HdfpNTZsKuLmPMHKUhYfBqhDkeAyNraVTEU3JhDwwiFZdxHi+6zAS1RI0a2GvR+Z2WdKF6e9ctP8bu7KEVP4Ra6DuKUl1jmEejs25P81SO2DVnDTnHnBaVKf1LdPq/lxHqV5MF2zbEZq/2i7a3epdwKw149oPl2IPUKui0hvE4+vTaBH8WzUP7wWxG/wqjOzOYaZgktgNck2ot6/EyJRHcuzfqSlHi5VZs+v3v2KYQ3bCPnng0YKumlbItuIWzbexcCf86vI80Fljz7tYtBriq3gT5L63puRXUuqjsLj9i7UF9n3p5k38e/Y9x1BoIXCY7oeKE/hDM2hMTBcBY6avolpw/bbGMIuz9uxpXxhzw23XCv89GDocYO/EFwKK/0eAPuxKUkjlGyczuG6Ak4gxRen0CRGHG1y+g7Z60WjJYpX5yB9vk6irEg1kvsqS1vRrTapv3GtIn72AYxo0MLUI33iQV1y4d6FRn91KQs7S20oumLvazvwzbFnyJ9gdK+9/ePG7pii4IZQzDRpAHU=
