language: ruby
script: "./build.sh"
branches:
  only:
  - gh-pages
rvm:
- 2.1.2
env:
  global:
    secure: vOhONHr0R2AmPfjisgcifrgmdFEq4M6WvCzULZLTI+L7oNqNF2mKh7+PyqMap9BruVSGa9TMncNSnobfTDIk9u583d5HZvo1F9GLJxT8CGzcMQh9MCxmm/QSXCBS0epZnggQBdKDeo6WtwMQWvyBqk3RS+LmLfJODQ8//E2qlg9hsX9SOkjnOFKjtXraZW1PmZUw8AHUxA7cEVDXI8QXLNkZx/GW7rBV4RfrhZWSlzRRE5pqJFxJAXWojeee+kpFcOsM9hBzoCPlwnojtd4ZKWLfDd56eecAtDDhgP7oPR1EjwZBZWpP6T6tXOqLQ6fEb2UtmtvyHLTM8im5G4vWtq3QGHhbchAwIM/LUSvZgaULreBh2scBj19/TQ06Qc/jITemF65stILE+zU6UGHKeRHQ2imF1WPGRWB9zYnPmYBFPnEVntvZXn3YKaQby6qBi4RtdW5JPVTDWjoJ1bpVdxeWA0cpBi7qqzC+10MGIvNEPHcOI3F3HMcb5L1OFBIsVkvNj1ll18b3YJyQlqJsGJR3aZ3olPLE/1+I3KIeNyu006k7ZW7KpDF7uAzA6hRhttdW1PGlpkxklswsB3Uaq60R606defBinAdJnXrTlk2PXdADOB7JRLJ7EYk63f1dwjRRK+POYbIRwKCe2ToRyiSHhAEHfNgfXRPf3MdMRBQ=
