---
title: Keaton Burleson
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
include:
- _pages
- _data
- assets/apps.scss
- _images
email: keaton.burleson@me.com
username: 128keaton
description: This is Keaton Burleson's website
baseurl: ''
url: ''
repo: 128keaton.com
branch: pre-publish
destination: ../site/
staticmanUrl: https://api.staticman.net/v2/entry/128keaton/128keaton.com/pre-publish/comments
markdown: kramdown
highlighter: rouge
encoding: utf-8
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- vendor
- README.md
- Rakefile
- changelog.md
- "*.Rmd"
- vendor
- .travis.yml
kramdown:
  input: GFM
---