---
title: Keaton Burleson
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
include:
- _pages
- _data
- assets/apps.scss
- _images
email: keaton.burleson@me.com
username: 128keaton
description: This is Keaton Burleson's website
baseurl: ''
url: ''
repo: 128keaton.com
branch: pre-publish
destination: ../site/
staticmanUrl: https://api.staticman.net/v2/entry/128keaton/128keaton.com/pre-publish/comments
markdown: kramdown
encoding: utf-8
gems:
- jekyll-feed
- jekyll-paginate-v2
exclude:
- Gemfile
- Gemfile.lock
kramdown:
  input: GFM

pagination:
  enabled: true
  debug: true
  collection: posts
  per_page: 5
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  trail:
    before: 2
    after: 2
